In [2]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler
X = np.array([[10],[20],[30],[40],[100]])
scaler = MinMaxScaler(feature_range=(0,1))
X_transformed = scaler.fit_transform(X)
print(X_transformed)

[[0.        ]
 [0.11111111]
 [0.22222222]
 [0.33333333]
 [1.        ]]


In [3]:
from sklearn.preprocessing import StandardScaler
X = np.array([[10],[20],[30],[40],[100]])
scaler = StandardScaler(feature_range=(0,1))
X_transformed = scaler.fit_transform(X)
print(X_transformed)

TypeError: StandardScaler.__init__() got an unexpected keyword argument 'feature_range'

In [5]:
import numpy as np
X = np.array([[10],[20],[30],[40],[100]])
j = len(str(np.max(np.abs(X))))
X_transformed = X/10**j
print(X_transformed)

[[0.01]
 [0.02]
 [0.03]
 [0.04]
 [0.1 ]]


In [ ]:
#Label encoding
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
cities = ['Kathmandu','Biratnagar','Butwal']
encoded = le.fit_transform(cities)
print(encoded)

[2 0 1]


In [7]:
#One hot encoding
import pandas as pd
df = pd.DataFrame({
     'country':['nepal','India','japan'],
    'source':['river','lake','well']
    })
df_encoded = pd.get_dummies(df,columns=['source'])
print(df_encoded)

  country  source_lake  source_river  source_well
0   nepal        False          True        False
1   India         True         False        False
2   japan        False         False         True


In [16]:
from sklearn.preprocessing import OrdinalEncoder
encoder = OrdinalEncoder(categories=[['poor','fair','good']])
quality = [['poor'],['good'],['fair']]
encoded = encoder.fit_transform(quality)
print(encoded)

[[0.]
 [2.]
 [1.]]


In [25]:
import numpy as np
X = np.random.random(10000000)
print(X[:5])
for i in range(X.shape[0]):
    X[i] = X[i] + 2
print(X[:5])


[0.68795057 0.9365261  0.64312651 0.64419746 0.84970166]
[2.68795057 2.9365261  2.64312651 2.64419746 2.84970166]


In [27]:
import numpy as np
X = np.random.random(100000000)
print(X[:5])
X = X + 2
print(X[:5])

[0.56876236 0.10794378 0.96378799 0.6932917  0.16132436]
[2.56876236 2.10794378 2.96378799 2.6932917  2.16132436]
